## SOFTMAX

SOFTMAX IMPLEMENTATION NUMPY

In [1]:
import numpy as np

#Method Implementation
def softmax_numpy(x):
    return np.exp(x) / np.sum(np.exp(x), axis = 0)

#Method Calling
x = np.array([2.0, 1.0, 0.1])
output = softmax_numpy(x)
print('softmax numpy : ', output)

softmax numpy :  [0.65900114 0.24243297 0.09856589]


SOFTMAX IMPLEMENTATION TORCH

In [2]:
import numpy as np
import torch

x = torch.tensor([2.0, 1.0, 0.1])
output = torch.softmax(x, dim=0)
print('softmax torch : ', output)

softmax torch :  tensor([0.6590, 0.2424, 0.0986])


CROSS-ENTROPY WITH SOFTMAX

Cross entropy loss is the most common loss function used to determine the losses in case of multi-class classification problem. One Hot Encoding is a must before applying the cross entropy loss.

IMPLEMENTATION OF CROSS-ENTROPY USING NUMPY

In [3]:
import torch
import torch.nn as nn
import numpy as np

def cross_entropy(actual, predicted):
    loss = -np.sum(actual * np.log(predicted))
    return loss

Y = np.array([1,0,0])

Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])
l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)
print(f'Loss1 numpy: {l1:.4f}')
print(f'Loss2 numpy: {l2:.4f}')

Loss1 numpy: 0.3567
Loss2 numpy: 2.3026


## nn.CrossEntropyLoss

CAREFUL

nn.CrossEntropyLoss applies `nn.LogSoftmax + nn.NLLLoss` (negative log likelihood loss)

--> No Softmax in the Last Layer

Y has class labels, not One-Hot!

Y_pred has raw scores (logits), no Softmax!

In [4]:
import torch
import torch.nn as nn
import numpy as np

loss = nn.CrossEntropyLoss()

#1 sample
Y = torch.tensor([0])

# n_sample * n_classes = 1 * 3
Y_pred_good = torch.tensor([[2.0, 0.3, 0.1]])
Y_pred_bad = torch.tensor([[0.5,2.0,0.3]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(l1.item())
print(l2.item())

0.2868707478046417
1.840616226196289


In [5]:
_, pred1 = torch.max(Y_pred_good, 1)
_, pred2 = torch.max(Y_pred_bad, 1)
print(pred1)
print(pred2)

tensor([0])
tensor([1])


IN CASE OF MULTI-CLASS CLASSIFICATION

In [6]:
import torch
import torch.nn as nn
import numpy as np

loss = nn.CrossEntropyLoss()

# 3 samples
Y = torch.tensor([2, 0, 1])

# n_sample * n_classes = 3 * 3
Y_pred_good = torch.tensor([[2.0, 0.1, 1.1], [1.4, 0.3, 1.0], [1.5, 0.3, 0.9]])
Y_pred_bad = torch.tensor([[2.3,1.0,0.3], [0.5,1.0,0.7], [2.5,0.8,0.5]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(l1.item())
print(l2.item())

1.2840458154678345
1.8904973268508911


In [8]:
_, pred1 = torch.max(Y_pred_good, 1)
_, pred2 = torch.max(Y_pred_bad, 1)
print(_, pred1)
print(_, pred2)

tensor([2.3000, 1.0000, 2.5000]) tensor([0, 0, 0])
tensor([2.3000, 1.0000, 2.5000]) tensor([0, 1, 0])
