In [1]:
import torch

DEFINING A TENSOR

In [2]:
x = torch.empty(1)
print(x)

tensor([1.7327e-35])


In [3]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


2D TENSOR

In [4]:
x = torch.empty(2,3)
print(x)

tensor([[1.7323e-35, 1.4013e-45, 1.7184e-35],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


3D TENSOR

In [5]:
x = torch.empty(2,2,3)
print(x)

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 9.8091e-45, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 1.4250e+01],
         [1.9403e-37, 5.7064e+01, 1.2146e-38]]])


EMPTY TENSOR IS BASICALLY CLOSE TO ZERO

RANDOM TENSOR

In [7]:
x = torch.rand(2,2,3)
print(x)

tensor([[[0.6091, 0.5888, 0.2876],
         [0.5270, 0.3014, 0.2088]],

        [[0.3917, 0.2292, 0.0541],
         [0.9499, 0.6858, 0.8220]]])


RANDOM VALUE TENSOR

In [8]:
x = torch.zeros(2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [9]:
x = torch.ones(2,2,3)
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [10]:
x = torch.ones(2,2,3, dtype = torch.float16)
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float16)


In [11]:
x = torch.ones(2,2,3, dtype = int)
print(x)

tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]])


In [12]:
x = torch.tensor([2.5, 0.15])
print(x)

tensor([2.5000, 0.1500])


TENSOR OPERATION

In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
print(z)

tensor([[0.8805, 0.8986],
        [0.4888, 0.7750]])
tensor([[0.9944, 0.8955],
        [0.9546, 0.0598]])
tensor([[1.8749, 1.7941],
        [1.4434, 0.8348]])


In [14]:
x = torch.rand(2,2)
y = torch.rand(2,2)
y.add_(x)
print(y)

tensor([[1.1005, 0.5335],
        [1.9658, 0.4056]])


In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.sub(x,y)
print(z)

tensor([[0.0922, 0.0760],
        [0.8210, 0.3774]])
tensor([[0.0864, 0.6495],
        [0.2420, 0.8196]])
tensor([[ 0.0058, -0.5735],
        [ 0.5789, -0.4422]])


In [16]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.mul(x,y)
print(z)

tensor([[0.3455, 0.6813],
        [0.9835, 0.6107]])
tensor([[0.7532, 0.4443],
        [0.3187, 0.7575]])
tensor([[0.2602, 0.3027],
        [0.3135, 0.4626]])


In [17]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.div(x,y)
print(z)

tensor([[0.1060, 0.8679],
        [0.4911, 0.9178]])
tensor([[0.2188, 0.5564],
        [0.9280, 0.9046]])
tensor([[0.4847, 1.5599],
        [0.5293, 1.0146]])


ELEMENTWISE OPERATION ON TENSOR

SLICING OPERATION IN TENSORS

In [20]:
x = torch.rand(5,4)
print(x)
print(x[:,0])
print(x[1,1])
print(x[1,1].item())

tensor([[0.2726, 0.3454, 0.1870, 0.2853],
        [0.1302, 0.3939, 0.6351, 0.3777],
        [0.6151, 0.2778, 0.9298, 0.1508],
        [0.7132, 0.6829, 0.0091, 0.0730],
        [0.0484, 0.4813, 0.5156, 0.2937]])
tensor([0.2726, 0.1302, 0.6151, 0.7132, 0.0484])
tensor(0.3939)
0.39393842220306396


RESHAPING IN TENSOR

In [22]:
x = torch.rand(4,3)
print(x)
y = x.view(12)
print(y)

tensor([[0.4292, 0.7204, 0.9344],
        [0.5604, 0.6427, 0.5334],
        [0.5268, 0.2975, 0.1961],
        [0.2305, 0.4784, 0.5214]])
tensor([0.4292, 0.7204, 0.9344, 0.5604, 0.6427, 0.5334, 0.5268, 0.2975, 0.1961,
        0.2305, 0.4784, 0.5214])


CONVERTING NUMPY TO TENSOR AND VICE VERSA

In [26]:
import torch
import numpy as np
a = torch.ones(5, dtype=int)
print(a)
b = a.numpy()
print(b)
print(type(b))
a.add_(2)
print(a)
print(b)

tensor([1, 1, 1, 1, 1])
[1 1 1 1 1]
<class 'numpy.ndarray'>
tensor([3, 3, 3, 3, 3])
[3 3 3 3 3]


BOTH a AND b POINT TO THE SAME MEMORY LOCATION

In [32]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


BOTH NUMPY AND TENSOR GOT MODIFIED

IMPORTANT:

We will implement requires_grad = True whenever we want to calculate gradient in order to minimize any loss in the problem. For that we will define the tensor as follows.

In [35]:
x = torch.rand(4,3, requires_grad = True)
print(x)

tensor([[0.3094, 0.8817, 0.8405],
        [0.5174, 0.6240, 0.8231],
        [0.4085, 0.3465, 0.1767],
        [0.6641, 0.0425, 0.9687]], requires_grad=True)
